/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as InfluencerRouteImport } from './routes/influencer'
import { Route as LoyaltyRouteImport } from './routes/loyalty'
import { Route as ManifestDotjsonRouteImport } from './routes/manifest[.]json'
import { Route as ManifestDotwebmanifestRouteImport } from './routes/manifest[.]webmanifest'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as PolicyRouteImport } from './routes/policy'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAbandonedCartsRouteImport } from './routes/admin.abandoned-carts'
import { Route as AdminAdProductsRouteImport } from './routes/admin.ad-products'
import { Route as AdminAdsRouteImport } from './routes/admin.ads'
import { Route as AdminAiCopyRouteImport } from './routes/admin.ai-copy'
import { Route as AdminAppearanceRouteImport } from './routes/admin.appearance'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminBannersRouteImport } from './routes/admin.banners'
import { Route as AdminBulkEditorRouteImport } from './routes/admin.bulk-editor'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminChangePasswordRouteImport } from './routes/admin.change-password'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AdminCouponsRouteImport } from './routes/admin.coupons'
import { Route as AdminCurrenciesRouteImport } from './routes/admin.currencies'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminDataRouteImport } from './routes/admin.data'
import { Route as AdminDeliveryRouteImport } from './routes/admin.delivery'
import { Route as AdminGoogleDriveRouteImport } from './routes/admin.google-drive'
import { Route as AdminInfluencersRouteImport } from './routes/admin.influencers'
import { Route as AdminInternalSettingsRouteImport } from './routes/admin.internal-settings'
import { Route as AdminInventoryRouteImport } from './routes/admin.inventory'
import { Route as AdminInvoicesRouteImport } from './routes/admin.invoices'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminLoyaltyRouteImport } from './routes/admin.loyalty'
import { Route as AdminMetaRouteImport } from './routes/admin.meta'
import { Route as AdminMetaGuideRouteImport } from './routes/admin.meta-guide'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminProfitsRouteImport } from './routes/admin.profits'
import { Route as AdminReviewsRouteImport } from './routes/admin.reviews'
import { Route as AdminSiteSettingsRouteImport } from './routes/admin.site-settings'
import { Route as AdminSuppliersRouteImport } from './routes/admin.suppliers'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as ApiEditMakeupRouteImport } from './routes/api/edit-makeup'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as ApiCronDriveSyncRouteImport } from './routes/api/cron/drive-sync'
import { Route as ApiPublicTrackRouteImport } from './routes/api/public/track'
import { Route as AuthMetaCallbackRouteImport } from './routes/auth/meta/callback'
import { Route as ApiAuthMetaCallbackRouteImport } from './routes/api/auth/meta/callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const InfluencerRoute = InfluencerRouteImport.update({
  id: '/influencer',
  path: '/influencer',
  getParentRoute: () => rootRouteImport,
} as any)
const LoyaltyRoute = LoyaltyRouteImport.update({
  id: '/loyalty',
  path: '/loyalty',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestDotjsonRoute = ManifestDotjsonRouteImport.update({
  id: '/manifest.json',
  path: '/manifest.json',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestDotwebmanifestRoute = ManifestDotwebmanifestRouteImport.update({
  id: '/manifest.webmanifest',
  path: '/manifest.webmanifest',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const PolicyRoute = PolicyRouteImport.update({
  id: '/policy',
  path: '/policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAbandonedCartsRoute = AdminAbandonedCartsRouteImport.update({
  id: '/abandoned-carts',
  path: '/abandoned-carts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdProductsRoute = AdminAdProductsRouteImport.update({
  id: '/ad-products',
  path: '/ad-products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdsRoute = AdminAdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiCopyRoute = AdminAiCopyRouteImport.update({
  id: '/ai-copy',
  path: '/ai-copy',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAppearanceRoute = AdminAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBannersRoute = AdminBannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBulkEditorRoute = AdminBulkEditorRouteImport.update({
  id: '/bulk-editor',
  path: '/bulk-editor',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChangePasswordRoute = AdminChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCouponsRoute = AdminCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCurrenciesRoute = AdminCurrenciesRouteImport.update({
  id: '/currencies',
  path: '/currencies',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDataRoute = AdminDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDeliveryRoute = AdminDeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGoogleDriveRoute = AdminGoogleDriveRouteImport.update({
  id: '/google-drive',
  path: '/google-drive',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInfluencersRoute = AdminInfluencersRouteImport.update({
  id: '/influencers',
  path: '/influencers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInternalSettingsRoute = AdminInternalSettingsRouteImport.update({
  id: '/internal-settings',
  path: '/internal-settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInvoicesRoute = AdminInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoyaltyRoute = AdminLoyaltyRouteImport.update({
  id: '/loyalty',
  path: '/loyalty',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMetaRoute = AdminMetaRouteImport.update({
  id: '/meta',
  path: '/meta',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMetaGuideRoute = AdminMetaGuideRouteImport.update({
  id: '/meta-guide',
  path: '/meta-guide',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfitsRoute = AdminProfitsRouteImport.update({
  id: '/profits',
  path: '/profits',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSiteSettingsRoute = AdminSiteSettingsRouteImport.update({
  id: '/site-settings',
  path: '/site-settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSuppliersRoute = AdminSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const ApiEditMakeupRoute = ApiEditMakeupRouteImport.update({
  id: '/api/edit-makeup',
  path: '/api/edit-makeup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCronDriveSyncRoute = ApiCronDriveSyncRouteImport.update({
  id: '/api/cron/drive-sync',
  path: '/api/cron/drive-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTrackRoute = ApiPublicTrackRouteImport.update({
  id: '/api/public/track',
  path: '/api/public/track',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthMetaCallbackRoute = AuthMetaCallbackRouteImport.update({
  id: '/meta/callback',
  path: '/meta/callback',
  getParentRoute: () => AuthRoute,
} as any)
const ApiAuthMetaCallbackRoute = ApiAuthMetaCallbackRouteImport.update({
  id: '/api/auth/meta/callback',
  path: '/api/auth/meta/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/compare': typeof CompareRoute
  '/connect': typeof ConnectRoute
  '/contact': typeof ContactRoute
  '/favorites': typeof FavoritesRoute
  '/influencer': typeof InfluencerRoute
  '/loyalty': typeof LoyaltyRoute
  '/manifest.json': typeof ManifestDotjsonRoute
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/mcp': typeof McpRoute
  '/orders': typeof OrdersRoute
  '/policy': typeof PolicyRoute
  '/products': typeof ProductsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studio': typeof StudioRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/abandoned-carts': typeof AdminAbandonedCartsRoute
  '/admin/ad-products': typeof AdminAdProductsRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/ai-copy': typeof AdminAiCopyRoute
  '/admin/appearance': typeof AdminAppearanceRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/bulk-editor': typeof AdminBulkEditorRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/change-password': typeof AdminChangePasswordRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/currencies': typeof AdminCurrenciesRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/data': typeof AdminDataRoute
  '/admin/delivery': typeof AdminDeliveryRoute
  '/admin/google-drive': typeof AdminGoogleDriveRoute
  '/admin/influencers': typeof AdminInfluencersRoute
  '/admin/internal-settings': typeof AdminInternalSettingsRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/invoices': typeof AdminInvoicesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/loyalty': typeof AdminLoyaltyRoute
  '/admin/meta': typeof AdminMetaRoute
  '/admin/meta-guide': typeof AdminMetaGuideRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/profits': typeof AdminProfitsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/site-settings': typeof AdminSiteSettingsRoute
  '/admin/suppliers': typeof AdminSuppliersRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/edit-makeup': typeof ApiEditMakeupRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/cron/drive-sync': typeof ApiCronDriveSyncRoute
  '/api/public/track': typeof ApiPublicTrackRoute
  '/auth/meta/callback': typeof AuthMetaCallbackRoute
  '/api/auth/meta/callback': typeof ApiAuthMetaCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRouteWithChildren
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/compare': typeof CompareRoute
  '/connect': typeof ConnectRoute
  '/contact': typeof ContactRoute
  '/favorites': typeof FavoritesRoute
  '/influencer': typeof InfluencerRoute
  '/loyalty': typeof LoyaltyRoute
  '/manifest.json': typeof ManifestDotjsonRoute
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/mcp': typeof McpRoute
  '/orders': typeof OrdersRoute
  '/policy': typeof PolicyRoute
  '/products': typeof ProductsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studio': typeof StudioRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/abandoned-carts': typeof AdminAbandonedCartsRoute
  '/admin/ad-products': typeof AdminAdProductsRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/ai-copy': typeof AdminAiCopyRoute
  '/admin/appearance': typeof AdminAppearanceRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/bulk-editor': typeof AdminBulkEditorRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/change-password': typeof AdminChangePasswordRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/currencies': typeof AdminCurrenciesRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/data': typeof AdminDataRoute
  '/admin/delivery': typeof AdminDeliveryRoute
  '/admin/google-drive': typeof AdminGoogleDriveRoute
  '/admin/influencers': typeof AdminInfluencersRoute
  '/admin/internal-settings': typeof AdminInternalSettingsRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/invoices': typeof AdminInvoicesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/loyalty': typeof AdminLoyaltyRoute
  '/admin/meta': typeof AdminMetaRoute
  '/admin/meta-guide': typeof AdminMetaGuideRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/profits': typeof AdminProfitsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/site-settings': typeof AdminSiteSettingsRoute
  '/admin/suppliers': typeof AdminSuppliersRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/edit-makeup': typeof ApiEditMakeupRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin': typeof AdminIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/cron/drive-sync': typeof ApiCronDriveSyncRoute
  '/api/public/track': typeof ApiPublicTrackRoute
  '/auth/meta/callback': typeof AuthMetaCallbackRoute
  '/api/auth/meta/callback': typeof ApiAuthMetaCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/compare': typeof CompareRoute
  '/connect': typeof ConnectRoute
  '/contact': typeof ContactRoute
  '/favorites': typeof FavoritesRoute
  '/influencer': typeof InfluencerRoute
  '/loyalty': typeof LoyaltyRoute
  '/manifest.json': typeof ManifestDotjsonRoute
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/mcp': typeof McpRoute
  '/orders': typeof OrdersRoute
  '/policy': typeof PolicyRoute
  '/products': typeof ProductsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studio': typeof StudioRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/abandoned-carts': typeof AdminAbandonedCartsRoute
  '/admin/ad-products': typeof AdminAdProductsRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/ai-copy': typeof AdminAiCopyRoute
  '/admin/appearance': typeof AdminAppearanceRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/bulk-editor': typeof AdminBulkEditorRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/change-password': typeof AdminChangePasswordRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/currencies': typeof AdminCurrenciesRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/data': typeof AdminDataRoute
  '/admin/delivery': typeof AdminDeliveryRoute
  '/admin/google-drive': typeof AdminGoogleDriveRoute
  '/admin/influencers': typeof AdminInfluencersRoute
  '/admin/internal-settings': typeof AdminInternalSettingsRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/invoices': typeof AdminInvoicesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/loyalty': typeof AdminLoyaltyRoute
  '/admin/meta': typeof AdminMetaRoute
  '/admin/meta-guide': typeof AdminMetaGuideRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/profits': typeof AdminProfitsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/site-settings': typeof AdminSiteSettingsRoute
  '/admin/suppliers': typeof AdminSuppliersRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/edit-makeup': typeof ApiEditMakeupRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/cron/drive-sync': typeof ApiCronDriveSyncRoute
  '/api/public/track': typeof ApiPublicTrackRoute
  '/auth/meta/callback': typeof AuthMetaCallbackRoute
  '/api/auth/meta/callback': typeof ApiAuthMetaCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/compare'
    | '/connect'
    | '/contact'
    | '/favorites'
    | '/influencer'
    | '/loyalty'
    | '/manifest.json'
    | '/manifest.webmanifest'
    | '/mcp'
    | '/orders'
    | '/policy'
    | '/products'
    | '/reset-password'
    | '/sitemap.xml'
    | '/studio'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/abandoned-carts'
    | '/admin/ad-products'
    | '/admin/ads'
    | '/admin/ai-copy'
    | '/admin/appearance'
    | '/admin/audit'
    | '/admin/banners'
    | '/admin/bulk-editor'
    | '/admin/categories'
    | '/admin/change-password'
    | '/admin/content'
    | '/admin/coupons'
    | '/admin/currencies'
    | '/admin/customers'
    | '/admin/data'
    | '/admin/delivery'
    | '/admin/google-drive'
    | '/admin/influencers'
    | '/admin/internal-settings'
    | '/admin/inventory'
    | '/admin/invoices'
    | '/admin/login'
    | '/admin/loyalty'
    | '/admin/meta'
    | '/admin/meta-guide'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/products'
    | '/admin/profits'
    | '/admin/reviews'
    | '/admin/site-settings'
    | '/admin/suppliers'
    | '/admin/users'
    | '/api/edit-makeup'
    | '/product/$slug'
    | '/admin/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/cron/drive-sync'
    | '/api/public/track'
    | '/auth/meta/callback'
    | '/api/auth/meta/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/auth'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/compare'
    | '/connect'
    | '/contact'
    | '/favorites'
    | '/influencer'
    | '/loyalty'
    | '/manifest.json'
    | '/manifest.webmanifest'
    | '/mcp'
    | '/orders'
    | '/policy'
    | '/products'
    | '/reset-password'
    | '/sitemap.xml'
    | '/studio'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/abandoned-carts'
    | '/admin/ad-products'
    | '/admin/ads'
    | '/admin/ai-copy'
    | '/admin/appearance'
    | '/admin/audit'
    | '/admin/banners'
    | '/admin/bulk-editor'
    | '/admin/categories'
    | '/admin/change-password'
    | '/admin/content'
    | '/admin/coupons'
    | '/admin/currencies'
    | '/admin/customers'
    | '/admin/data'
    | '/admin/delivery'
    | '/admin/google-drive'
    | '/admin/influencers'
    | '/admin/internal-settings'
    | '/admin/inventory'
    | '/admin/invoices'
    | '/admin/login'
    | '/admin/loyalty'
    | '/admin/meta'
    | '/admin/meta-guide'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/products'
    | '/admin/profits'
    | '/admin/reviews'
    | '/admin/site-settings'
    | '/admin/suppliers'
    | '/admin/users'
    | '/api/edit-makeup'
    | '/product/$slug'
    | '/admin'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/cron/drive-sync'
    | '/api/public/track'
    | '/auth/meta/callback'
    | '/api/auth/meta/callback'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/compare'
    | '/connect'
    | '/contact'
    | '/favorites'
    | '/influencer'
    | '/loyalty'
    | '/manifest.json'
    | '/manifest.webmanifest'
    | '/mcp'
    | '/orders'
    | '/policy'
    | '/products'
    | '/reset-password'
    | '/sitemap.xml'
    | '/studio'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/abandoned-carts'
    | '/admin/ad-products'
    | '/admin/ads'
    | '/admin/ai-copy'
    | '/admin/appearance'
    | '/admin/audit'
    | '/admin/banners'
    | '/admin/bulk-editor'
    | '/admin/categories'
    | '/admin/change-password'
    | '/admin/content'
    | '/admin/coupons'
    | '/admin/currencies'
    | '/admin/customers'
    | '/admin/data'
    | '/admin/delivery'
    | '/admin/google-drive'
    | '/admin/influencers'
    | '/admin/internal-settings'
    | '/admin/inventory'
    | '/admin/invoices'
    | '/admin/login'
    | '/admin/loyalty'
    | '/admin/meta'
    | '/admin/meta-guide'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/products'
    | '/admin/profits'
    | '/admin/reviews'
    | '/admin/site-settings'
    | '/admin/suppliers'
    | '/admin/users'
    | '/api/edit-makeup'
    | '/product/$slug'
    | '/admin/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/cron/drive-sync'
    | '/api/public/track'
    | '/auth/meta/callback'
    | '/api/auth/meta/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  CartRoute: typeof CartRoute
  CategoriesRoute: typeof CategoriesRoute
  CheckoutRoute: typeof CheckoutRoute
  CompareRoute: typeof CompareRoute
  ConnectRoute: typeof ConnectRoute
  ContactRoute: typeof ContactRoute
  FavoritesRoute: typeof FavoritesRoute
  InfluencerRoute: typeof InfluencerRoute
  LoyaltyRoute: typeof LoyaltyRoute
  ManifestDotjsonRoute: typeof ManifestDotjsonRoute
  ManifestDotwebmanifestRoute: typeof ManifestDotwebmanifestRoute
  McpRoute: typeof McpRoute
  OrdersRoute: typeof OrdersRoute
  PolicyRoute: typeof PolicyRoute
  ProductsRoute: typeof ProductsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StudioRoute: typeof StudioRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiEditMakeupRoute: typeof ApiEditMakeupRoute
  ProductSlugRoute: typeof ProductSlugRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiCronDriveSyncRoute: typeof ApiCronDriveSyncRoute
  ApiPublicTrackRoute: typeof ApiPublicTrackRoute
  ApiAuthMetaCallbackRoute: typeof ApiAuthMetaCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/influencer': {
      id: '/influencer'
      path: '/influencer'
      fullPath: '/influencer'
      preLoaderRoute: typeof InfluencerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loyalty': {
      id: '/loyalty'
      path: '/loyalty'
      fullPath: '/loyalty'
      preLoaderRoute: typeof LoyaltyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifest.json': {
      id: '/manifest.json'
      path: '/manifest.json'
      fullPath: '/manifest.json'
      preLoaderRoute: typeof ManifestDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifest.webmanifest': {
      id: '/manifest.webmanifest'
      path: '/manifest.webmanifest'
      fullPath: '/manifest.webmanifest'
      preLoaderRoute: typeof ManifestDotwebmanifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policy': {
      id: '/policy'
      path: '/policy'
      fullPath: '/policy'
      preLoaderRoute: typeof PolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/abandoned-carts': {
      id: '/admin/abandoned-carts'
      path: '/abandoned-carts'
      fullPath: '/admin/abandoned-carts'
      preLoaderRoute: typeof AdminAbandonedCartsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ad-products': {
      id: '/admin/ad-products'
      path: '/ad-products'
      fullPath: '/admin/ad-products'
      preLoaderRoute: typeof AdminAdProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ads': {
      id: '/admin/ads'
      path: '/ads'
      fullPath: '/admin/ads'
      preLoaderRoute: typeof AdminAdsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ai-copy': {
      id: '/admin/ai-copy'
      path: '/ai-copy'
      fullPath: '/admin/ai-copy'
      preLoaderRoute: typeof AdminAiCopyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/appearance': {
      id: '/admin/appearance'
      path: '/appearance'
      fullPath: '/admin/appearance'
      preLoaderRoute: typeof AdminAppearanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/banners': {
      id: '/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AdminBannersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bulk-editor': {
      id: '/admin/bulk-editor'
      path: '/bulk-editor'
      fullPath: '/admin/bulk-editor'
      preLoaderRoute: typeof AdminBulkEditorRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/change-password': {
      id: '/admin/change-password'
      path: '/change-password'
      fullPath: '/admin/change-password'
      preLoaderRoute: typeof AdminChangePasswordRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coupons': {
      id: '/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminCouponsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/currencies': {
      id: '/admin/currencies'
      path: '/currencies'
      fullPath: '/admin/currencies'
      preLoaderRoute: typeof AdminCurrenciesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/data': {
      id: '/admin/data'
      path: '/data'
      fullPath: '/admin/data'
      preLoaderRoute: typeof AdminDataRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/delivery': {
      id: '/admin/delivery'
      path: '/delivery'
      fullPath: '/admin/delivery'
      preLoaderRoute: typeof AdminDeliveryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/google-drive': {
      id: '/admin/google-drive'
      path: '/google-drive'
      fullPath: '/admin/google-drive'
      preLoaderRoute: typeof AdminGoogleDriveRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/influencers': {
      id: '/admin/influencers'
      path: '/influencers'
      fullPath: '/admin/influencers'
      preLoaderRoute: typeof AdminInfluencersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/internal-settings': {
      id: '/admin/internal-settings'
      path: '/internal-settings'
      fullPath: '/admin/internal-settings'
      preLoaderRoute: typeof AdminInternalSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/invoices': {
      id: '/admin/invoices'
      path: '/invoices'
      fullPath: '/admin/invoices'
      preLoaderRoute: typeof AdminInvoicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/loyalty': {
      id: '/admin/loyalty'
      path: '/loyalty'
      fullPath: '/admin/loyalty'
      preLoaderRoute: typeof AdminLoyaltyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/meta': {
      id: '/admin/meta'
      path: '/meta'
      fullPath: '/admin/meta'
      preLoaderRoute: typeof AdminMetaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/meta-guide': {
      id: '/admin/meta-guide'
      path: '/meta-guide'
      fullPath: '/admin/meta-guide'
      preLoaderRoute: typeof AdminMetaGuideRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profits': {
      id: '/admin/profits'
      path: '/profits'
      fullPath: '/admin/profits'
      preLoaderRoute: typeof AdminProfitsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/site-settings': {
      id: '/admin/site-settings'
      path: '/site-settings'
      fullPath: '/admin/site-settings'
      preLoaderRoute: typeof AdminSiteSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/suppliers': {
      id: '/admin/suppliers'
      path: '/suppliers'
      fullPath: '/admin/suppliers'
      preLoaderRoute: typeof AdminSuppliersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/edit-makeup': {
      id: '/api/edit-makeup'
      path: '/api/edit-makeup'
      fullPath: '/api/edit-makeup'
      preLoaderRoute: typeof ApiEditMakeupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/drive-sync': {
      id: '/api/cron/drive-sync'
      path: '/api/cron/drive-sync'
      fullPath: '/api/cron/drive-sync'
      preLoaderRoute: typeof ApiCronDriveSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/track': {
      id: '/api/public/track'
      path: '/api/public/track'
      fullPath: '/api/public/track'
      preLoaderRoute: typeof ApiPublicTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/meta/callback': {
      id: '/auth/meta/callback'
      path: '/meta/callback'
      fullPath: '/auth/meta/callback'
      preLoaderRoute: typeof AuthMetaCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/auth/meta/callback': {
      id: '/api/auth/meta/callback'
      path: '/api/auth/meta/callback'
      fullPath: '/api/auth/meta/callback'
      preLoaderRoute: typeof ApiAuthMetaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAbandonedCartsRoute: typeof AdminAbandonedCartsRoute
  AdminAdProductsRoute: typeof AdminAdProductsRoute
  AdminAdsRoute: typeof AdminAdsRoute
  AdminAiCopyRoute: typeof AdminAiCopyRoute
  AdminAppearanceRoute: typeof AdminAppearanceRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminBannersRoute: typeof AdminBannersRoute
  AdminBulkEditorRoute: typeof AdminBulkEditorRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminChangePasswordRoute: typeof AdminChangePasswordRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminCouponsRoute: typeof AdminCouponsRoute
  AdminCurrenciesRoute: typeof AdminCurrenciesRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminDataRoute: typeof AdminDataRoute
  AdminDeliveryRoute: typeof AdminDeliveryRoute
  AdminGoogleDriveRoute: typeof AdminGoogleDriveRoute
  AdminInfluencersRoute: typeof AdminInfluencersRoute
  AdminInternalSettingsRoute: typeof AdminInternalSettingsRoute
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminInvoicesRoute: typeof AdminInvoicesRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminLoyaltyRoute: typeof AdminLoyaltyRoute
  AdminMetaRoute: typeof AdminMetaRoute
  AdminMetaGuideRoute: typeof AdminMetaGuideRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminProfitsRoute: typeof AdminProfitsRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminSiteSettingsRoute: typeof AdminSiteSettingsRoute
  AdminSuppliersRoute: typeof AdminSuppliersRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAbandonedCartsRoute: AdminAbandonedCartsRoute,
  AdminAdProductsRoute: AdminAdProductsRoute,
  AdminAdsRoute: AdminAdsRoute,
  AdminAiCopyRoute: AdminAiCopyRoute,
  AdminAppearanceRoute: AdminAppearanceRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminBannersRoute: AdminBannersRoute,
  AdminBulkEditorRoute: AdminBulkEditorRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminChangePasswordRoute: AdminChangePasswordRoute,
  AdminContentRoute: AdminContentRoute,
  AdminCouponsRoute: AdminCouponsRoute,
  AdminCurrenciesRoute: AdminCurrenciesRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminDataRoute: AdminDataRoute,
  AdminDeliveryRoute: AdminDeliveryRoute,
  AdminGoogleDriveRoute: AdminGoogleDriveRoute,
  AdminInfluencersRoute: AdminInfluencersRoute,
  AdminInternalSettingsRoute: AdminInternalSettingsRoute,
  AdminInventoryRoute: AdminInventoryRoute,
  AdminInvoicesRoute: AdminInvoicesRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminLoyaltyRoute: AdminLoyaltyRoute,
  AdminMetaRoute: AdminMetaRoute,
  AdminMetaGuideRoute: AdminMetaGuideRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminProfitsRoute: AdminProfitsRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminSiteSettingsRoute: AdminSiteSettingsRoute,
  AdminSuppliersRoute: AdminSuppliersRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthRouteChildren {
  AuthMetaCallbackRoute: typeof AuthMetaCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthMetaCallbackRoute: AuthMetaCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  CartRoute: CartRoute,
  CategoriesRoute: CategoriesRoute,
  CheckoutRoute: CheckoutRoute,
  CompareRoute: CompareRoute,
  ConnectRoute: ConnectRoute,
  ContactRoute: ContactRoute,
  FavoritesRoute: FavoritesRoute,
  InfluencerRoute: InfluencerRoute,
  LoyaltyRoute: LoyaltyRoute,
  ManifestDotjsonRoute: ManifestDotjsonRoute,
  ManifestDotwebmanifestRoute: ManifestDotwebmanifestRoute,
  McpRoute: McpRoute,
  OrdersRoute: OrdersRoute,
  PolicyRoute: PolicyRoute,
  ProductsRoute: ProductsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StudioRoute: StudioRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiEditMakeupRoute: ApiEditMakeupRoute,
  ProductSlugRoute: ProductSlugRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiCronDriveSyncRoute: ApiCronDriveSyncRoute,
  ApiPublicTrackRoute: ApiPublicTrackRoute,
  ApiAuthMetaCallbackRoute: ApiAuthMetaCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
